services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/venv # Don't overwrite the container's venv with the host's
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite:///./app/trafivista.db
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Don't overwrite the container's node_modules with the host's
    depends_on:
      - backend
    restart: always
